<?php

// Catálogo canónico protestante (66 libros).
// Fuente de verdad para seeds, URLs (slug) y ReferenceParser (aliases).

return [
    ['ord' => 1,  'osis' => 'GEN', 'name' => 'Génesis',          'slug' => 'genesis',            'aliases' => 'génesis,genesis,gen,gn',                                          'testament' => 'AT', 'chapters' => 50],
    ['ord' => 2,  'osis' => 'EXO', 'name' => 'Éxodo',            'slug' => 'exodo',              'aliases' => 'éxodo,exodo,exo,ex',                                              'testament' => 'AT', 'chapters' => 40],
    ['ord' => 3,  'osis' => 'LEV', 'name' => 'Levítico',         'slug' => 'levitico',           'aliases' => 'levítico,levitico,lev,lv',                                        'testament' => 'AT', 'chapters' => 27],
    ['ord' => 4,  'osis' => 'NUM', 'name' => 'Números',          'slug' => 'numeros',            'aliases' => 'números,numeros,num,nm',                                          'testament' => 'AT', 'chapters' => 36],
    ['ord' => 5,  'osis' => 'DEU', 'name' => 'Deuteronomio',     'slug' => 'deuteronomio',       'aliases' => 'deuteronomio,deut,dt',                                            'testament' => 'AT', 'chapters' => 34],
    ['ord' => 6,  'osis' => 'JOS', 'name' => 'Josué',            'slug' => 'josue',              'aliases' => 'josué,josue,jos',                                                 'testament' => 'AT', 'chapters' => 24],
    ['ord' => 7,  'osis' => 'JDG', 'name' => 'Jueces',           'slug' => 'jueces',             'aliases' => 'jueces,jue,juec',                                                 'testament' => 'AT', 'chapters' => 21],
    ['ord' => 8,  'osis' => 'RUT', 'name' => 'Rut',              'slug' => 'rut',                'aliases' => 'rut,ruth,rt',                                                     'testament' => 'AT', 'chapters' => 4],
    ['ord' => 9,  'osis' => '1SA', 'name' => '1 Samuel',         'slug' => '1-samuel',           'aliases' => '1 samuel,primer samuel,primera samuel,1 sam,1sa,1 sa',             'testament' => 'AT', 'chapters' => 31],
    ['ord' => 10, 'osis' => '2SA', 'name' => '2 Samuel',         'slug' => '2-samuel',           'aliases' => '2 samuel,segundo samuel,segunda samuel,2 sam,2sa,2 sa',            'testament' => 'AT', 'chapters' => 24],
    ['ord' => 11, 'osis' => '1KI', 'name' => '1 Reyes',          'slug' => '1-reyes',            'aliases' => '1 reyes,primer reyes,primera reyes,1 rey,1re,1 re',                'testament' => 'AT', 'chapters' => 22],
    ['ord' => 12, 'osis' => '2KI', 'name' => '2 Reyes',          'slug' => '2-reyes',            'aliases' => '2 reyes,segundo reyes,segunda reyes,2 rey,2re,2 re',               'testament' => 'AT', 'chapters' => 25],
    ['ord' => 13, 'osis' => '1CH', 'name' => '1 Crónicas',       'slug' => '1-cronicas',         'aliases' => '1 crónicas,1 cronicas,primer crónicas,1 cro,1 cr,1ch',             'testament' => 'AT', 'chapters' => 29],
    ['ord' => 14, 'osis' => '2CH', 'name' => '2 Crónicas',       'slug' => '2-cronicas',         'aliases' => '2 crónicas,2 cronicas,segundo crónicas,2 cro,2 cr,2ch',            'testament' => 'AT', 'chapters' => 36],
    ['ord' => 15, 'osis' => 'ESD', 'name' => 'Esdras',           'slug' => 'esdras',             'aliases' => 'esdras,esd',                                                       'testament' => 'AT', 'chapters' => 10],
    ['ord' => 16, 'osis' => 'NEH', 'name' => 'Nehemías',         'slug' => 'nehemias',           'aliases' => 'nehemías,nehemias,neh',                                            'testament' => 'AT', 'chapters' => 13],
    ['ord' => 17, 'osis' => 'EST', 'name' => 'Ester',            'slug' => 'ester',              'aliases' => 'ester,est',                                                        'testament' => 'AT', 'chapters' => 10],
    ['ord' => 18, 'osis' => 'JOB', 'name' => 'Job',              'slug' => 'job',                'aliases' => 'job,jb',                                                           'testament' => 'AT', 'chapters' => 42],
    ['ord' => 19, 'osis' => 'PSA', 'name' => 'Salmos',           'slug' => 'salmos',             'aliases' => 'salmos,salmo,sal,sl,salm,ps',                                      'testament' => 'AT', 'chapters' => 150],
    ['ord' => 20, 'osis' => 'PRO', 'name' => 'Proverbios',       'slug' => 'proverbios',         'aliases' => 'proverbios,proverbio,prov,pro,pr',                                 'testament' => 'AT', 'chapters' => 31],
    ['ord' => 21, 'osis' => 'ECC', 'name' => 'Eclesiastés',      'slug' => 'eclesiastes',        'aliases' => 'eclesiastés,eclesiastes,ecl,ec',                                   'testament' => 'AT', 'chapters' => 12],
    ['ord' => 22, 'osis' => 'SNG', 'name' => 'Cantares',         'slug' => 'cantares',           'aliases' => 'cantares,cantar de los cantares,cantar,cnt',                       'testament' => 'AT', 'chapters' => 8],
    ['ord' => 23, 'osis' => 'ISA', 'name' => 'Isaías',           'slug' => 'isaias',             'aliases' => 'isaías,isaias,isa,is',                                             'testament' => 'AT', 'chapters' => 66],
    ['ord' => 24, 'osis' => 'JER', 'name' => 'Jeremías',         'slug' => 'jeremias',           'aliases' => 'jeremías,jeremias,jer,jr',                                         'testament' => 'AT', 'chapters' => 52],
    ['ord' => 25, 'osis' => 'LAM', 'name' => 'Lamentaciones',    'slug' => 'lamentaciones',      'aliases' => 'lamentaciones,lam,lm',                                             'testament' => 'AT', 'chapters' => 5],
    ['ord' => 26, 'osis' => 'EZK', 'name' => 'Ezequiel',         'slug' => 'ezequiel',           'aliases' => 'ezequiel,eze,ezq',                                                 'testament' => 'AT', 'chapters' => 48],
    ['ord' => 27, 'osis' => 'DAN', 'name' => 'Daniel',           'slug' => 'daniel',             'aliases' => 'daniel,dan,dn',                                                    'testament' => 'AT', 'chapters' => 12],
    ['ord' => 28, 'osis' => 'HOS', 'name' => 'Oseas',            'slug' => 'oseas',              'aliases' => 'oseas,os',                                                         'testament' => 'AT', 'chapters' => 14],
    ['ord' => 29, 'osis' => 'JOL', 'name' => 'Joel',             'slug' => 'joel',               'aliases' => 'joel,jl',                                                          'testament' => 'AT', 'chapters' => 3],
    ['ord' => 30, 'osis' => 'AMO', 'name' => 'Amós',             'slug' => 'amos',               'aliases' => 'amós,amos,am',                                                     'testament' => 'AT', 'chapters' => 9],
    ['ord' => 31, 'osis' => 'OBA', 'name' => 'Abdías',           'slug' => 'abdias',             'aliases' => 'abdías,abdias,abd',                                                'testament' => 'AT', 'chapters' => 1],
    ['ord' => 32, 'osis' => 'JON', 'name' => 'Jonás',            'slug' => 'jonas',              'aliases' => 'jonás,jonas,jon',                                                  'testament' => 'AT', 'chapters' => 4],
    ['ord' => 33, 'osis' => 'MIC', 'name' => 'Miqueas',          'slug' => 'miqueas',            'aliases' => 'miqueas,miq',                                                      'testament' => 'AT', 'chapters' => 7],
    ['ord' => 34, 'osis' => 'NAH', 'name' => 'Nahúm',            'slug' => 'nahum',              'aliases' => 'nahúm,nahum,nah',                                                  'testament' => 'AT', 'chapters' => 3],
    ['ord' => 35, 'osis' => 'HAB', 'name' => 'Habacuc',          'slug' => 'habacuc',            'aliases' => 'habacuc,hab',                                                      'testament' => 'AT', 'chapters' => 3],
    ['ord' => 36, 'osis' => 'ZEP', 'name' => 'Sofonías',         'slug' => 'sofonias',           'aliases' => 'sofonías,sofonias,sof',                                             'testament' => 'AT', 'chapters' => 3],
    ['ord' => 37, 'osis' => 'HAG', 'name' => 'Hageo',            'slug' => 'hageo',              'aliases' => 'hageo,hag',                                                        'testament' => 'AT', 'chapters' => 2],
    ['ord' => 38, 'osis' => 'ZEC', 'name' => 'Zacarías',         'slug' => 'zacarias',           'aliases' => 'zacarías,zacarias,zac',                                             'testament' => 'AT', 'chapters' => 14],
    ['ord' => 39, 'osis' => 'MAL', 'name' => 'Malaquías',        'slug' => 'malaquias',          'aliases' => 'malaquías,malaquias,mal',                                           'testament' => 'AT', 'chapters' => 4],
    ['ord' => 40, 'osis' => 'MAT', 'name' => 'Mateo',            'slug' => 'mateo',              'aliases' => 'mateo,mat,mt,evangelio de mateo',                                  'testament' => 'NT', 'chapters' => 28],
    ['ord' => 41, 'osis' => 'MRK', 'name' => 'Marcos',           'slug' => 'marcos',             'aliases' => 'marcos,mar,mr,mc,evangelio de marcos',                             'testament' => 'NT', 'chapters' => 16],
    ['ord' => 42, 'osis' => 'LUK', 'name' => 'Lucas',            'slug' => 'lucas',              'aliases' => 'lucas,luc,lc,evangelio de lucas',                                  'testament' => 'NT', 'chapters' => 24],
    ['ord' => 43, 'osis' => 'JHN', 'name' => 'Juan',             'slug' => 'juan',               'aliases' => 'juan,jn,evangelio de juan,evangelio según juan',                   'testament' => 'NT', 'chapters' => 21],
    ['ord' => 44, 'osis' => 'ACT', 'name' => 'Hechos',           'slug' => 'hechos',             'aliases' => 'hechos,hech,hch,act,hechos de los apóstoles',                      'testament' => 'NT', 'chapters' => 28],
    ['ord' => 45, 'osis' => 'ROM', 'name' => 'Romanos',          'slug' => 'romanos',            'aliases' => 'romanos,rom,ro',                                                   'testament' => 'NT', 'chapters' => 16],
    ['ord' => 46, 'osis' => '1CO', 'name' => '1 Corintios',      'slug' => '1-corintios',        'aliases' => '1 corintios,primera corintios,primer corintios,1 cor,1co,1 co',    'testament' => 'NT', 'chapters' => 16],
    ['ord' => 47, 'osis' => '2CO', 'name' => '2 Corintios',      'slug' => '2-corintios',        'aliases' => '2 corintios,segunda corintios,segundo corintios,2 cor,2co,2 co',   'testament' => 'NT', 'chapters' => 13],
    ['ord' => 48, 'osis' => 'GAL', 'name' => 'Gálatas',          'slug' => 'galatas',            'aliases' => 'gálatas,galatas,gal,ga',                                           'testament' => 'NT', 'chapters' => 6],
    ['ord' => 49, 'osis' => 'EPH', 'name' => 'Efesios',          'slug' => 'efesios',            'aliases' => 'efesios,efe,ef',                                                   'testament' => 'NT', 'chapters' => 6],
    ['ord' => 50, 'osis' => 'PHP', 'name' => 'Filipenses',       'slug' => 'filipenses',         'aliases' => 'filipenses,fil,flp',                                               'testament' => 'NT', 'chapters' => 4],
    ['ord' => 51, 'osis' => 'COL', 'name' => 'Colosenses',       'slug' => 'colosenses',         'aliases' => 'colosenses,col',                                                   'testament' => 'NT', 'chapters' => 4],
    ['ord' => 52, 'osis' => '1TH', 'name' => '1 Tesalonicenses', 'slug' => '1-tesalonicenses',   'aliases' => '1 tesalonicenses,primera tesalonicenses,1 tes,1th,1 ts',           'testament' => 'NT', 'chapters' => 5],
    ['ord' => 53, 'osis' => '2TH', 'name' => '2 Tesalonicenses', 'slug' => '2-tesalonicenses',   'aliases' => '2 tesalonicenses,segunda tesalonicenses,2 tes,2th,2 ts',           'testament' => 'NT', 'chapters' => 3],
    ['ord' => 54, 'osis' => '1TI', 'name' => '1 Timoteo',        'slug' => '1-timoteo',          'aliases' => '1 timoteo,primera timoteo,primer timoteo,1 tim,1ti',               'testament' => 'NT', 'chapters' => 6],
    ['ord' => 55, 'osis' => '2TI', 'name' => '2 Timoteo',        'slug' => '2-timoteo',          'aliases' => '2 timoteo,segunda timoteo,segundo timoteo,2 tim,2ti',              'testament' => 'NT', 'chapters' => 4],
    ['ord' => 56, 'osis' => 'TIT', 'name' => 'Tito',             'slug' => 'tito',               'aliases' => 'tito,tit',                                                         'testament' => 'NT', 'chapters' => 3],
    ['ord' => 57, 'osis' => 'PHM', 'name' => 'Filemón',          'slug' => 'filemon',            'aliases' => 'filemón,filemon,flm',                                              'testament' => 'NT', 'chapters' => 1],
    ['ord' => 58, 'osis' => 'HEB', 'name' => 'Hebreos',          'slug' => 'hebreos',            'aliases' => 'hebreos,heb',                                                      'testament' => 'NT', 'chapters' => 13],
    ['ord' => 59, 'osis' => 'JAS', 'name' => 'Santiago',         'slug' => 'santiago',           'aliases' => 'santiago,sant,stg',                                                'testament' => 'NT', 'chapters' => 5],
    ['ord' => 60, 'osis' => '1PE', 'name' => '1 Pedro',          'slug' => '1-pedro',            'aliases' => '1 pedro,primera pedro,primer pedro,1 pe,1pe,1 ped',                'testament' => 'NT', 'chapters' => 5],
    ['ord' => 61, 'osis' => '2PE', 'name' => '2 Pedro',          'slug' => '2-pedro',            'aliases' => '2 pedro,segunda pedro,segundo pedro,2 pe,2pe,2 ped',               'testament' => 'NT', 'chapters' => 3],
    ['ord' => 62, 'osis' => '1JN', 'name' => '1 Juan',           'slug' => '1-juan',             'aliases' => '1 juan,primera juan,primer juan,1 jn,1jn',                         'testament' => 'NT', 'chapters' => 5],
    ['ord' => 63, 'osis' => '2JN', 'name' => '2 Juan',           'slug' => '2-juan',             'aliases' => '2 juan,segunda juan,segundo juan,2 jn,2jn',                        'testament' => 'NT', 'chapters' => 1],
    ['ord' => 64, 'osis' => '3JN', 'name' => '3 Juan',           'slug' => '3-juan',             'aliases' => '3 juan,tercera juan,tercer juan,3 jn,3jn',                         'testament' => 'NT', 'chapters' => 1],
    ['ord' => 65, 'osis' => 'JUD', 'name' => 'Judas',            'slug' => 'judas',              'aliases' => 'judas,jud',                                                        'testament' => 'NT', 'chapters' => 1],
    ['ord' => 66, 'osis' => 'REV', 'name' => 'Apocalipsis',      'slug' => 'apocalipsis',        'aliases' => 'apocalipsis,apo,apoc,rev,revelación',                              'testament' => 'NT', 'chapters' => 22],
];
